if: (branch = master) OR (type = pull_request) OR (tag =~ /^\d+\.\d+\.\d+(-.*)?$/)

stages:
  - name: validate tests
  - name: test
  - name: publish docs
    if: tag =~ /^\d+\.\d+\.\d+(-.*)?$/

os: osx
language: swift

jobs:
  include:
    - stage: validate tests
      name: Validate SwiftPM generated linux test files
      osx_image: xcode11.4
      script: swift test --generate-linuxmain && git diff --exit-code

    - &linux
      stage: test
      name: SwiftPM Linux Release
      os: linux
      dist: bionic
      language: generic
      addons:
        apt:
          update: true
          packages:
            - libatomic1
            - libbsd0
            - libcurl4
            - libxml2
            - libedit2
            - libsqlite3-0
            - libc6-dev
            - binutils
            - libgcc-5-dev
            - libstdc++-5-dev
            - libpython2.7
            - tzdata
            - git
            - pkg-config
            - curl
            - libldap2-dev
      env:
        - SWIFT_SKIP_APT=1
        - SWIFT_INSTALL_TARGET="./.swift"
        - SWIFT_PLATFORM="ubuntu18.04"
        - SWIFT_BRANCH="swift-5.2.1-release"
        - SWIFT_VERSION="swift-5.2.1-RELEASE"
      install: eval "$(curl -fsL 'https://bitbucket.org/!api/2.0/snippets/sersoftgmbh/7AgnAp/files/install_swift_linux.sh')"
      script: ./.swift/usr/bin/swift test --parallel --enable-code-coverage
      after_success:
        - ./.swift/usr/bin/llvm-cov export -format="lcov" .build/debug/*PackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
        - bash <(curl -fsL https://codecov.io/bash)

    - <<: *linux
      name: SwiftPM Linux Beta
      env:
        - SWIFT_SKIP_APT=1
        - SWIFT_INSTALL_TARGET="./.swift"
        - SWIFT_PLATFORM="ubuntu18.04"
        - SWIFT_BRANCH="swift-5.2-branch"
        - SWIFT_VERSION="swift-5.2-DEVELOPMENT-SNAPSHOT-2020-03-24-a"

    - &macOS
      stage: test
      name: SwiftPM macOS Release
      osx_image: xcode11.4
      script: swift test --parallel --enable-code-coverage
      after_success:
        - xcrun llvm-cov export -format="lcov" .build/debug/*PackageTests.xctest/Contents/MacOS/*PackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
        - bash <(curl -fsL https://codecov.io/bash)

    # - <<: *macOS
    #   name: SwiftPM macOS Beta
    #   osx_image: xcode12

    - stage: publish docs
      name: Generate and publish documentation
      osx_image: xcode11.4
      install:
        - brew install sourcekitten
        - gem install jazzy
      script:
        - sourcekitten doc --spm-module SwiftDirector > docs.json
        - jazzy --sourcekitten-sourcefile docs.json --module-version $TRAVIS_TAG
      deploy:
        provider: pages
        github-token: $GITHUB_DOCS_TOKEN
        skip-cleanup: true
        local-dir: docs
        target_branch: gh-pages
        on:
          tags: true
