name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-11, ubuntu-18.04, ubuntu-20.04 ]
        swift-version: [ 5.5, 5.6 ]

    runs-on: ${{matrix.os}}
    steps:
      - name: Install OpenLDAP
        if: runner.os == 'Linux'
        run: sudo apt-get install libldap2-dev
      - uses: swift-actions/setup-swift@v1.15.0
        id: swift-setup
        with:
          swift-version: ${{matrix.swift-version}}
      - name: Read OS Version
        uses: sersoft-gmbh/os-version-action@v1.0.0
        id: os-version
      - uses: actions/checkout@v3.0.2
      - uses: actions/cache@v3.0.2
        with:
          path: .build
          key: ${{runner.os}}-${{steps.os-version.outputs.version}}-${{github.repository}}-spm-${{steps.swift-setup.outputs.version}}-${{hashFiles('**/Package.resolved')}}
          restore-keys: |
            ${{runner.os}}-${{steps.os-version.outputs.version}}-${{github.repository}}-spm-${{steps.swift-setup.outputs.version}}-
      - name: Build & Test
        run: swift test -v --parallel --enable-code-coverage
      - name: Generate Coverage Files
        uses: sersoft-gmbh/swift-coverage-action@v2.0.1
        id: coverage-files
        with:
          format: lcov
      - uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ${{join(fromJSON(steps.coverage-files.outputs.files), ',')}}
          fail_ci_if_error: true
