name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-linux-tests:
    runs-on: macos-latest
    steps:
      - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
      - uses: actions/checkout@v2
      - name: Generate Linux Tests
        run: swift test --generate-linuxmain
      - name: Check for git differences
        run: git diff --exit-code
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]

    runs-on: ${{matrix.os}}

    steps:
    - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
      if: runner.os == 'macOS'
    - name: Install OpenLDAP
      if: runner.os == 'Linux'
      run: sudo apt-get install libldap2-dev
    - name: Install Swift
      if: runner.os == 'Linux'
      uses: sersoft-gmbh/SwifyActions@v1
      with:
        release-version: 5.2.2
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v --parallel
