name: Swift Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-linux-tests:
    runs-on: macos-latest
    steps:
      - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
      - uses: actions/checkout@v2
      - name: Generate Linux Tests
        run: swift test --generate-linuxmain
      - name: Check for git differences
        run: git diff --exit-code
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]

    runs-on: ${{matrix.os}}

    steps:
    - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
      if: runner.os == 'macOS'
    - name: Install OpenLDAP
      if: runner.os == 'Linux'
      run: sudo apt-get install libldap2-dev
    - name: Install Swift
      if: runner.os == 'Linux'
      env:
        SWIFT_SKIP_APT: 0
        SWIFT_INSTALL_TARGET: "/"
        SWIFT_PLATFORM: "ubuntu18.04"
        SWIFT_BRANCH: "swift-5.2.1-release"
        SWIFT_VERSION: "swift-5.2.1-RELEASE"
      run: |
        curl -fsL 'https://bitbucket.org/!api/2.0/snippets/sersoftgmbh/7AgnAp/files/install_swift_linux.sh') -o install_swift.sh
        chmod +x install_swift.sh
        sudo ./install_swift.sh
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --parallel
